# GitHub Pages設定
theme: null
plugins: []

# ファイルを除外しない設定
include:
  - service-worker.js
  - manifest.json
  - _*

# キャッシュ無効化のためのクエリパラメータ追加
# これによりService Workerの更新が確実に行われる
defaults:
  - scope:
      path: "service-worker.js"
    values:
      cache_control: "no-cache, no-store, must-revalidate"